name: Update Notion with Steam Data

on:
  schedule:
    - cron: "5 22,06,14 * * *"
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update notion games
        env:
          STEAM_API_KEY: ${{ 6FB855571831133221578119C2ADBAC9 }}
          STEAM_USER_ID: ${{ 76561198950877329 }}
          NOTION_API_KEY: ${{ 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 }}
          NOTION_DATABASE_ID: ${{ 191fe034c75f80f7870dcd8b783c3006 }}
          include_played_free_games: ${{true}}
          enable_item_update: ${{false}}
          enable_filter: ${{true}}
        run: python main.py
